### ISSUE TITLE
Issues running module

### ISSUE THREAD

**Issue by ofello** [swimlane/PSCVSS#1]
First off, thanks for making this. Excited to test is out.

Second, I'm fairly new to PowerShell, so some of the install/pathing stuff is a bit beyond me at the moment.

That said, you had one of your files with a wrong extension. Correcting that fixed one of the issues. But now I'm getting the following:

![image](https://user-images.githubusercontent.com/54186907/78275717-95e7ab80-74d7-11ea-9c58-d30170071908.png)

This is after following your install instructions. Any help would be appreciated. Thanks!

**Comment by joshswimlane** [comment]
@ofello So sorry for the delay here - I just pushed a new version up and should be deployed to the powershell gallery soon.  My apologies again!

**Comment by mladjen** [comment]
Hi @joshswimlane,

Also super keen to start using this module. but i seem to be having the same issue as @ofello.

Simply running install-module and import-module does not work. Could you please look into this issue.

Cheers!

**Comment by joshswimlane** [comment]
@mladjen I will take care of this tomorrow - not sure what happened here.  My apologies.

**Comment by martintoreilly** [comment]
Hi @joshswimlane. Thanks for writing this module.I'm looking forward to using it, but I'm experiencing a very similar error to the one @ofello reported. I am using the latest version 2.03 of PSCVSS.

I installed PSCVSS v2.03 from `PSGallery` using `Install-Module PSCVSS`. When I run `Import-Module -Name PSCVSS -Force`, I get the error below. I am running PowerShell Core 7.0.1 on macOS Mojave (version 10.14.5).

![image](https://user-images.githubusercontent.com/21147592/82856329-99127d00-9f05-11ea-871e-4e9d3f57bb1a.png)

Looking at the `InvalidOperation` error, it looks like PowerShell is looking for the `BaseScore.psm1` module in a `PSCVSS/Class/` directory within my current working directory. Could this be an issue with resolving relative paths?

I cloned this repository and `Import-Module -Name PSCVSS -Force` works when invoked from the repository root folder.

Could part of the problem be https://github.com/PowerShell/PowerShell/issues/7424, where relative paths in `using module` directives aren't treated as relative to the enclosing a script unless they begin with `\`, rather than `/`?

Looking at `PSCVSS/PSCVSS/PSCVSS.psm1` I see the `using module` directives begin with `/` and, if I change these to begin with `\` the path to the `BaseScore.psm1` shown in the `InvalidOperation` now reads the actual location of that file as installed on my system. Note that it was only necessary to change the first `/` to `\` to get the change in file path the error message, but as I was still getting an error, I tried replacing all the `/`s with `\`s. However, that did not fix the error and I am now stuck. Any ideas?

![image](https://user-images.githubusercontent.com/21147592/82858918-22797d80-9f0d-11ea-804c-4d5a22a59e22.png)

![image](https://user-images.githubusercontent.com/21147592/82858807-d4647a00-9f0c-11ea-8d01-548a736d970e.png)

![image](https://user-images.githubusercontent.com/21147592/82858854-f2ca7580-9f0c-11ea-9299-c9baef5c23d8.png)

**Comment by martintoreilly** [comment]
Aha! There's an extra `PSCVSS` between `2.0.2` and `Class` in the path listed in the `InvalidOperation` error! Hopefully dropping the `PVCSS\` part from the relative paths in `PSCVSS.psm1` will do the trick.

**Comment by martintoreilly** [comment]
🎉🎉🎉

Success! Pull request incoming.

![image](https://user-images.githubusercontent.com/21147592/82859720-6a999f80-9f0f-11ea-9967-ff054b84ba7f.png)

🎉🎉🎉

**Comment by martintoreilly** [comment]
PR #2 awaiting review.
